FROM apache/airflow:2.7.3

# Copiar requirements.txt
COPY requirements.txt /tmp/requirements.txt

# Instalar dependencias como usuario airflow
USER airflow
RUN pip install --no-cache-dir --user -r /tmp/requirements.txt

# Volver a la configuración por defecto
USER root